# Generated by Django 3.1.7 on 2021-03-31 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='size',
            new_name='preferred_size',
        ),
    ]
