# Generated by Django 3.1.7 on 2021-04-02 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210331_1236'),
        ('account', '0002_auto_20210331_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_size',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.productsize'),
            preserve_default=False,
        ),
    ]
