# Generated by Django 3.1.7 on 2021-03-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
